oisdk/team-software-project

backend/tests/test_roll_die.py

test_numbers_rolled was originally written in lower camel case by mistake.

Use snake case instead of lower camel case

---

frontend/app/index.js
frontend/app/random.js
frontend/app/random.test.js
frontend/app/sendJSON.js
frontend/app/sendJSON.test.js
frontend/package.json

The ajax logic is currently commented out because I don't know how it can be tested without a server who can ACK the ajax request

Javascript send json

---

backend/backend/process_client_json.py

Calling this function with the dice roll for the client gives the JSON response string to send.

Add function to generate JSON response

---

backend/backend/process_client_json.py
backend/pages.py
backend/tests/test_process_client_json.py
frontend/app/index.js
frontend/app/sendJSON.js
frontend/app/sendJSON.test.js

it looks like the way to handle post requests is very different from the way to handle forms

Handle post request, (not forms)

---

frontend/html/index.html

Added the form for taking username input.

Add username input textbox

---

backend/backend/process_client_json.py
backend/pages.py

Implement receive_client_username

Server echo username to client

---

local_deploy.ps1

Couldn't get the local_deploy.sh script going on windows. This works instead.

added local_deploy powershell script for windows

---

frontend/app/create-join-game.html
frontend/app/generateCreateJoinGamePage.js
frontend/app/generateCreateJoinGamePage.test.js
frontend/app/index.js

As confusing as this may seem, this branch actually includes my work on _both_ task 1.2 and task 3.1. All task 1.2 work is in index.js so at least that makes it easier to understand. Task 3.1 is in files generateCreateJoinGamePage.js and create-join-game.html.

Js request either create username or create/join game page - JS generates create/join game page

---

frontend/app/sendJSON.js
frontend/app/sendJSON.test.js

I wrote a generic sendJSON function so that I wouldn’t have to deal directly with creating XMLHttpRequests too much, and I’ve put it on its own branch to try and get it into master quickly.
I haven’t written the tests for it yet, but how does it look?

Generic send json

---

frontend/app/createUserCookie.js
frontend/app/createUserCookie.test.js

Create user cookie

---

frontend/app/checkButton.js
frontend/app/checkButton.test.js
frontend/app/generateUsernameForm.js
frontend/app/generateUsernameForm.test.js
frontend/app/index.js
frontend/html/index.html

Once the checkbox is checked, the textbox will be disabled ensuring no changes made to username and rolling die function is enabled. checkButton.js file is used for the checking and changing the corresponding tag attribute value.

Confirm username for client

---

frontend/app/checkUserIDCookie.js
frontend/app/generateCreateJoinGamePage.js
frontend/app/index.js
frontend/app/pickGame.js

I just added some jsdoc to functions I contributed to the most after agreeing on this form of documentation in the last Sprint meeting. I tidied up the pickGame.js mock as well (no functional changes, just layout).

arhh adds some jsdoc

---

backend/backend/dummy_game_details.py
backend/pages.py
frontend/app/pages.js
frontend/app/pages.test.js

Opening this early. I’ve got 3.1 as finished as possible for the moment – need to co-ordinate with @gabystephanov on the details.
I’m gonna add task 3.2 to this, so that I can start on it immediately, rather than waiting till this is merged into master.
I’m not sure if it makes sense to add testing for dummy functions that I’m going to remove when merging the code?

3.1 & 3.2: Javascript function waitingGame

---

backend/backend/game.py
backend/backend/get_list_of_games.py
backend/backend/request_game_list.py
backend/pages.py
backend/requirements.txt
backend/tests/test_get_list_of_games.py
backend/tests/test_request_game_list.py

Considering the storage is a mock one, the class Game is used to instantiate mock existing games and are returned in a list. This can be improved by instead providing the game information in a JSON file {game_id : game_info} but perhaps that is a later to-have discussion!

Get list of games

---

frontend/package.json

Leaving function threshold at 50% to encourage some bit of testing.
Since @oisdk and @undergroundquizscene have contributed to package.json, I would like if ye reviewed it just in case I'm missing something. The changes seem to work for me anyway.

Change Jest's coverageThreshold fields to '0' (not including functions)

---

frontend/app/createGame.js

@arhh any more changes needed?

now passes host_id in json

---

backend/backend/game.py
backend/backend/player.py
backend/backend/roll_die.py
backend/pages.py

Rolls two dice for a player, updates the position, rolls and turn in the database and adds money if they pass go. Also fixed some SQL errors in game.py and player.py

Update player position with dice roll

---

frontend/css/default.css
frontend/html/index.html

The page is split in 3 columns. The left div has the id 'content-left', the center div has id 'content' , the right div has id 'content-right'. Their size is split up 3/12 | 6/12 | 3/12 respectively.

Content layout in the html.

---

frontend/app/generateCreateJoinGamePage.js
frontend/app/generateCreateJoinGamePage.test.js
frontend/app/generateUsernameForm.js
frontend/app/generateUsernameForm.test.js
frontend/app/pages.js
frontend/app/pages.test.js
frontend/app/pickGame.js
frontend/app/pickGame.test.js

Please let me know if i missed something or messed something up! I made some quick adjustments to the tests in order to pass.

Fixes to the HTML. Generated HTML should now be generated in the innerHTML of <div id="content">

---

CONTRIBUTING.md

Feel free to add/change. Just trying to finish the misc tasks remaining.

html conventions summary

---

backend/backend/events.py
backend/backend/join_game.py
backend/backend/start_game.py
backend/pages.py
frontend/app/pages.js

I've been very lazy with tests lately so I decided to make a pull request and then deal with the tests.
The biggest change I made to these files (besides the task work) is add comments which hopefully helps anyone wanting a few SSE tidbits.
I'm not sure why pickGame is no longer "default" in master (which is merged with this branch) anymore so hopefully that doesn't cause problems.

Check waiting game issue game start

---

README.md

Hopefully this makes it easier to know what's laid out behind the scenes :slightly_smiling_face: .
If there's something inaccurate or missing, let me know.

Add Database Schema to Top-Level README

---

backend/README.md

This should take the bother of learning reStructuredText off our backs.

Update and Rename README.rst to README.md

---

frontend/app/createGame.js
frontend/app/pickGame.js
frontend/app/waitingGame.js
frontend/app/waitingGame.test.js

Until we decide on an organisation for our frontend code, I think it makes more sense to be consistent with the rest of the code, so I’m putting this functionality in its own module.

Move waitingGame to its own file

---

backend/README.rst

Reverts oisdk/team-software-project#93

Revert "Update and Rename README.rst to README.md"

---

frontend/app/activeGame.js
frontend/app/generateGameInterface.js

Don't know what happened the old pull request for this, it seems to have merged itself in without actually merging?

Ignore console.log() warnings

---

backend/backend/roll_die.py
frontend/app/updateRollButton.js
frontend/app/updateRollButton.test.js
frontend/package.json

UpdateRollButton now calls the player_roll_die to handle updating the states of the player attributes and rolling of the dice. It retrieves the rolls from the module and compares them and changes the state of the button on the client-side according to whether the rolls are equal (roll button is enabled) or not (roll button is disabled).

Update roll button

---

CONTRIBUTING.md

I made a few changes to the layout of the Markdown tables as well, but adding properties schema is the primary reason for this pull request.

Add "properties" and "property_values" schema to CONTRIBUTING.md

---

backend/backend/check_position.py

A very small addition just to keep the code as integrated as possible.

check_position() calls jail_player()

---

frontend/app/activeGame.js
frontend/app/generateGameLog.js

Just finishing off task 8.1 with a log function for when a property changes owner.

Properties logging

---

backend/backend/game.py
initialise_server.sql

With these fixes, I can get to the waiting game, and in the games table, I see a game listed, so it should be fixed.

Pre-Populate Properties Fix

---

frontend/app/activeGame.js
frontend/app/checkUserIDCookie.js
frontend/app/createGame.js
frontend/app/displayBuildings.js
frontend/app/generateCreateJoinGamePage.js
frontend/app/generateGameLog.js
frontend/app/generateUserDetails.js
frontend/app/moveFunctions.js
frontend/app/pickGame.js
frontend/app/waitingGame.js

I’ve added some @module tags and @private tags to make the jsdoc a bit more navigable.

Update jsdoc to make it more navigable
